#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar  2 13:40:48 2022

@author: ninekinnman
"""


import matplotlib.pyplot as plt

import numpy as np

import csv

file = open('cumulative_cases_28022022.csv')

csvreader = csv.reader(file)